#
# Demos (v1.0.0): .travis.yml
# Copyright (c) 2019 Adorade. All Rights Reserved.
# Licensed under MIT
#
# Travis continuous integration system configuration file.
# Overview on how to customize the configuration is located at:
# http://docs.travis-ci.com/user/customizing-the-build/

language: node_js

node_js:
  - "lts/*"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH

cache:
  yarn: true

before_script:
  - yarn global add gulp-cli
  - node -v && npm -v && yarn -v && git --version && gulp -v

script:
  - yarn run build
